### ISSUE TITLE
Crash Upon Death

### ISSUE THREAD

**Issue by Timashy** [portablejim/Audio-Death#3]
Everytime I die using forge in 1.12.2 on servers, the game crashes.  Works fine with singleplayer.  Love this mod and hope you fix it. 👍

**Comment by TheDarkAngel7** [comment]
I did have the same issue: Here's the complete log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 5/9/19 10:14 PM
Description: Unexpected error

java.lang.IllegalArgumentException: value already present: net.minecraft.client.audio.PositionedSoundRecord@3be1d479
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
	at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:430)
	at net.minecraft.client.audio.SoundHandler.func_147682_a(SoundHandler.java:258)
	at portablejim.audiodeath.proxy.ClientProxy.handleDeath(ClientProxy.java:33)
	at portablejim.audiodeath.AudioDeath.deathScreen(AudioDeath.java:83)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_AudioDeath_deathScreen_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:983)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1737)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
	at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:430)
	at net.minecraft.client.audio.SoundHandler.func_147682_a(SoundHandler.java:258)

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.2.0
	Minecraft version: Minecraft 1.12.2 (1.12.2/fml,forge,LiteLoader/Forge)
	Expected version: 1.12.2
	Protocol version: 340
	Data version: 1343
	File location: ~~ERROR~~ IllegalArgumentException: URI is not hierarchical
Stacktrace:
	at java.lang.Thread.getStackTrace(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_85073_a(CrashReportCategory.java:116)
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:352)
	at wdl.WDL.addInfoToCrash(WDL.java:1539)
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:378)
	at net.minecraft.crash.CrashReport.handler$onCrashReportPopulateEnvironment$zze000(CrashReport.java:531)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:144)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@3d82c5f3 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@3d82c5f3 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: net.minecraft.client.Minecraft@4667c6d9
	worldClient: net.minecraft.client.multiplayer.WorldClient@45a80d53
	networkManager: net.minecraft.network.NetworkManager@2589cdfc
	thePlayer: EntityPlayerSP['TheDarkAngel7'/1397242, l='MpServer', x=196.71, y=59.17, z=4138.08]
	windowContainer: net.minecraft.inventory.ContainerPlayer@33c7476c
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: true
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: 
	baseFolderName: Empire_Minecraft

-- World Downloader Mod - Base properties --
Details:
	Messages.enableAll: true
	Messages.REMOVE_ENTITY: false
	Messages.UPDATES: true
	Messages.PLUGIN_CHANNEL_MESSAGE: false
	Messages.INFO: true
	Messages.ON_MAP_SAVED: false
	LinkedWorlds: 
	Messages.UPDATE_DEBUG: false
	Messages.LOAD_TILE_ENTITY: false
	ServerName: Empire Minecraft
	LastSaved: 1556054699681
	Messages.ON_WORLD_LOAD: false
	Messages.SAVING: true
	Messages.ON_CHUNK_NO_LONGER_NEEDED: false

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: "d76677e946f3a6b433d86bfa653527b9"

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheDarkAngel7'/1397242, l='MpServer', x=196.71, y=59.17, z=4138.08]]
	Chunk stats: MultiplayerChunkCache: 170, 170
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 112385 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 100 total; [EntityPigZombie['Zombie Pigman'/279300, l='MpServer', x=228.50, y=45.00, z=4079.50], EntityItem['item.tile.hellrock'/285956, l='MpServer', x=195.65, y=58.82, z=4138.01], EntityItem['item.item.appleGold'/285957, l='MpServer', x=195.69, y=58.83, z=4137.98], EntityItem['item.tile.shulkerBoxPurple'/285958, l='MpServer', x=195.59, y=58.81, z=4137.99], EntityItem['item.item.bootsDiamond'/285959, l='MpServer', x=195.65, y=58.65, z=4138.01], EntityItem['item.tile.shulkerBoxBlue'/285952, l='MpServer', x=195.65, y=58.81, z=4138.01], EntityPlayerSP['TheDarkAngel7'/1397242, l='MpServer', x=196.71, y=59.17, z=4138.08], EntityPigZombie['Zombie Pigman'/279297, l='MpServer', x=187.54, y=91.00, z=4101.50], EntityItem['item.item.flint'/285953, l='MpServer', x=195.60, y=58.68, z=4138.00], EntityItem['item.item.sulphur'/285954, l='MpServer', x=195.68, y=59.02, z=4138.02], EntityItem['item.item.skull.char'/285955, l='MpServer', x=195.64, y=58.97, z=4137.99], EntityTippedArrow['Arrow'/285455, l='MpServer', x=205.80, y=57.02, z=4130.08], EntityItem['item.item.leggingsDiamond'/285960, l='MpServer', x=195.62, y=58.78, z=4138.02], EntityItem['item.item.chestplateDiamond'/285961, l='MpServer', x=195.68, y=58.65, z=4137.99], EntityItem['item.item.helmetDiamond'/285962, l='MpServer', x=195.65, y=58.76, z=4138.02], EntityItem['item.item.skull.char'/285963, l='MpServer', x=196.33, y=59.32, z=4137.80], EntityXPOrb['Experience Orb'/285717, l='MpServer', x=207.23, y=57.00, z=4131.31], EntityPigZombie['Zombie Pigman'/284972, l='MpServer', x=207.50, y=41.00, z=4181.50], EntityPigZombie['Zombie Pigman'/284205, l='MpServer', x=228.51, y=49.00, z=4116.23], EntityPigZombie['Zombie Pigman'/281134, l='MpServer', x=235.63, y=89.00, z=4134.02], EntityPigZombie['Zombie Pigman'/283176, l='MpServer', x=251.72, y=89.00, z=4091.57], EntityPigZombie['Zombie Pigman'/285225, l='MpServer', x=185.98, y=35.00, z=4130.52], EntityXPOrb['Experience Orb'/278836, l='MpServer', x=214.75, y=77.00, z=4153.92], EntityPigZombie['Zombie Pigman'/281142, l='MpServer', x=206.50, y=84.00, z=4170.50], EntityPigZombie['Zombie Pigman'/279356, l='MpServer', x=254.32, y=52.00, z=4114.78], EntityMagmaCube['Magma Cube'/285244, l='MpServer', x=174.62, y=85.00, z=4156.28], EntityPigZombie['Zombie Pigman'/283961, l='MpServer', x=194.50, y=13.00, z=4178.50], EntityMagmaCube['Magma Cube'/285242, l='MpServer', x=183.60, y=84.00, z=4158.92], EntityMagmaCube['Magma Cube'/285243, l='MpServer', x=178.78, y=84.00, z=4159.05], EntityPigZombie['Zombie Pigman'/279364, l='MpServer', x=213.23, y=89.00, z=4117.78], EntityPigZombie['Zombie Pigman'/285253, l='MpServer', x=215.50, y=18.00, z=4093.50], EntityPigZombie['Zombie Pigman'/282178, l='MpServer', x=194.50, y=44.00, z=4173.50], EntityPigZombie['Zombie Pigman'/279363, l='MpServer', x=208.22, y=90.00, z=4121.50], EntityPigZombie['Zombie Pigman'/282708, l='MpServer', x=191.50, y=14.00, z=4166.50], EntityPigZombie['Zombie Pigman'/279127, l='MpServer', x=195.75, y=58.00, z=4147.21], EntityPigZombie['Zombie Pigman'/279632, l='MpServer', x=182.50, y=115.00, z=4149.50], EntityWolf['§cNetherhound'/283474, l='MpServer', x=192.43, y=58.00, z=4135.90], EntityWolf['§cNetherhound'/283475, l='MpServer', x=194.70, y=58.00, z=4136.68], EntityPigZombie['Zombie Pigman'/279635, l='MpServer', x=258.50, y=94.00, z=4167.50], EntityPigZombie['Zombie Pigman'/285020, l='MpServer', x=204.50, y=12.00, z=4191.50], EntityPigZombie['Zombie Pigman'/285022, l='MpServer', x=236.50, y=33.00, z=4186.50], EntityPigZombie['Zombie Pigman'/279128, l='MpServer', x=200.93, y=58.00, z=4140.19], EntityPigZombie['Zombie Pigman'/285287, l='MpServer', x=190.20, y=58.00, z=4151.25], EntityTippedArrow['Arrow'/285536, l='MpServer', x=207.13, y=57.03, z=4128.90], EntityPigZombie['Zombie Pigman'/285035, l='MpServer', x=180.50, y=61.00, z=4106.50], EntityPigZombie['Zombie Pigman'/279924, l='MpServer', x=184.50, y=36.00, z=4136.81], EntityPigZombie['Zombie Pigman'/279411, l='MpServer', x=222.50, y=89.00, z=4122.50], EntityPigZombie['Zombie Pigman'/282744, l='MpServer', x=239.21, y=90.00, z=4109.80], EntityPigZombie['Zombie Pigman'/279686, l='MpServer', x=184.50, y=13.00, z=4168.50], EntityPigZombie['Zombie Pigman'/281728, l='MpServer', x=258.50, y=62.00, z=4175.50], EntityPigZombie['Zombie Pigman'/284033, l='MpServer', x=235.50, y=32.00, z=4188.50], EntityPigZombie['Zombie Pigman'/280974, l='MpServer', x=258.50, y=62.00, z=4168.50], EntityPigZombie['Zombie Pigman'/280975, l='MpServer', x=236.50, y=69.00, z=4082.77], EntityPigZombie['Zombie Pigman'/279957, l='MpServer', x=183.27, y=66.00, z=4117.45], EntityPigZombie['Zombie Pigman'/279958, l='MpServer', x=188.14, y=66.00, z=4117.64], EntityPigZombie['Zombie Pigman'/285853, l='MpServer', x=153.50, y=49.00, z=4125.50], EntityPigZombie['Zombie Pigman'/281247, l='MpServer', x=209.78, y=91.00, z=4088.82], EntityPigZombie['Zombie Pigman'/285851, l='MpServer', x=155.50, y=49.00, z=4129.50], EntityPigZombie['Zombie Pigman'/282784, l='MpServer', x=209.50, y=58.00, z=4113.50], EntityPigZombie['Zombie Pigman'/284832, l='MpServer', x=223.50, y=41.00, z=4112.50], EntityTippedArrow['Arrow'/285887, l='MpServer', x=186.10, y=58.01, z=4147.05], EntityTippedArrow['Arrow'/285893, l='MpServer', x=191.12, y=58.03, z=4139.81], EntityPigZombie['Zombie Pigman'/280779, l='MpServer', x=181.50, y=91.00, z=4083.50], EntityPigZombie['Zombie Pigman'/285910, l='MpServer', x=172.50, y=66.00, z=4081.50], EntityItem['item.tile.hellrock'/285911, l='MpServer', x=209.13, y=59.00, z=4140.88], EntityPigZombie['Zombie Pigman'/284880, l='MpServer', x=213.50, y=103.00, z=4193.50], EntityPigZombie['Zombie Pigman'/285907, l='MpServer', x=180.50, y=92.00, z=4100.50], EntityPigZombie['Zombie Pigman'/279262, l='MpServer', x=210.82, y=59.00, z=4150.55], EntityPigZombie['Zombie Pigman'/283102, l='MpServer', x=238.50, y=89.00, z=4099.50], EntityPigZombie['Zombie Pigman'/279512, l='MpServer', x=250.50, y=58.00, z=4160.50], EntityPigZombie['Zombie Pigman'/285400, l='MpServer', x=168.40, y=43.00, z=4123.73], EntityItem['item.tile.hellrock'/285912, l='MpServer', x=176.48, y=57.00, z=4128.96], EntityTippedArrow['Arrow'/285401, l='MpServer', x=190.91, y=58.00, z=4142.68], EntityPigZombie['Zombie Pigman'/285915, l='MpServer', x=257.50, y=53.00, z=4111.50], EntityItem['item.item.sulphur'/285666, l='MpServer', x=209.25, y=57.00, z=4129.64], EntityPigZombie['Zombie Pigman'/284387, l='MpServer', x=233.50, y=34.00, z=4170.50], EntityItem['item.item.beefCooked'/285932, l='MpServer', x=195.62, y=58.74, z=4138.02], EntityItem['item.item.fireworks'/285933, l='MpServer', x=195.67, y=58.92, z=4138.02], EntityItem['item.item.netherquartz'/285934, l='MpServer', x=195.63, y=59.09, z=4137.96], EntityItem['item.tile.hellrock'/285935, l='MpServer', x=195.65, y=58.65, z=4138.01], EntityPigZombie['Zombie Pigman'/280809, l='MpServer', x=207.50, y=83.00, z=4153.50], EntityItem['item.item.pickaxeDiamond'/285931, l='MpServer', x=195.66, y=58.75, z=4137.99], EntityItem['item.item.netherquartz'/285940, l='MpServer', x=195.66, y=58.70, z=4138.06], EntityItem['item.item.netherquartz'/285941, l='MpServer', x=195.67, y=58.71, z=4138.03], EntityItem['item.item.blazePowder'/285942, l='MpServer', x=195.64, y=58.90, z=4138.02], EntityPigZombie['Zombie Pigman'/280567, l='MpServer', x=181.50, y=116.00, z=4155.50], EntityItem['item.item.potion'/285943, l='MpServer', x=195.67, y=58.85, z=4137.96], EntityItem['item.item.arrow'/285936, l='MpServer', x=195.63, y=58.73, z=4138.00], EntityPigZombie['Zombie Pigman'/279537, l='MpServer', x=253.19, y=52.00, z=4125.25], EntityItem['item.tile.shulkerBoxPurple'/285937, l='MpServer', x=195.66, y=58.79, z=4138.01], EntityItem['item.item.netherquartz'/285938, l='MpServer', x=195.64, y=59.01, z=4138.00], EntityItem['item.item.netherquartz'/285939, l='MpServer', x=195.68, y=58.82, z=4137.99], EntityItem['item.item.netherquartz'/285948, l='MpServer', x=195.66, y=58.89, z=4137.99], EntityItem['item.item.netherquartz'/285949, l='MpServer', x=195.65, y=58.84, z=4138.01], EntityItem['item.item.netherquartz'/285950, l='MpServer', x=195.68, y=58.75, z=4138.00], EntityItem['item.tile.shulkerBoxRed'/285951, l='MpServer', x=195.68, y=58.85, z=4137.98], EntityItem['item.item.elytra'/285944, l='MpServer', x=195.64, y=58.88, z=4137.99], EntityItem['item.item.netherquartz'/285945, l='MpServer', x=195.61, y=58.84, z=4137.99], EntityItem['item.item.diamond'/285946, l='MpServer', x=195.65, y=58.85, z=4138.01], EntityItem['item.item.magmaCream'/285947, l='MpServer', x=195.66, y=58.80, z=4138.00]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.13-SNAPSHOT:60d1eea:231) <- Paper
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 745896424 bytes (711 MB) / 1275068416 bytes (1216 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E1 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                    | Source                                                       | Signature                                |
	|:------ |:--------------------- |:-------------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| UCHIJA | minecraft             | 1.12.2                     | minecraft.jar                                                | None                                     |
	| UCHIJA | mcp                   | 9.42                       | minecraft.jar                                                | None                                     |
	| UCHIJA | FML                   | 8.0.99.99                  | forge-1.12.2-14.23.5.2768.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                 | 14.23.5.2768               | forge-1.12.2-14.23.5.2768.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | additionalresources   | 0.1.1                      | additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar        | None                                     |
	| UCHIJA | audiodeath            | 0.7.0_1.9-87aeca7          | audiodeath-1.9-0.7.0.50+87aeca7.jar                          | None                                     |
	| UCHIJA | easiervillagertrading | 1.2                        | easiervillagertrading-1.12-forge14.21.1.2387-1.2.jar         | None                                     |
	| UCHIJA | emcshoplocator        | 1.6                        | EMCShopLocator-1.12-forge14.21.1.2387-1.6.jar                | None                                     |
	| UCHIJA | lunatriuscore         | 1.2.0.42                   | LunatriusCore-1.12.2-1.2.0.42-universal.jar                  | None                                     |
	| UCHIJA | schematica            | 1.8.0.167                  | Schematica-1.12.2-1.8.0.167-universal.jar                    | None                                     |
	| UCHIJA | worldeditcuife2       | 2.1.2-mf-1.12-14.21.1.2387 | WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12-14.21.1.2387.jar | None                                     |

	Loaded coremods (and transformers): 
Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.39' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.39, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180626-134842
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 430.39
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
